# Generated by Django 5.1 on 2024-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Lady', 'Lady'), ('Rev', 'Rev'), ('Lord', 'Lord'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dame', 'Dame'), ('Mx', 'Mx'), ('Miss', 'Miss')], max_length=5),
        ),
    ]
