# Generated by Django 5.1 on 2024-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Lady', 'Lady'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx'), ('Miss', 'Miss'), ('Rev', 'Rev'), ('Lord', 'Lord'), ('Dame', 'Dame')], max_length=5),
        ),
    ]
