# Generated by Django 5.1 on 2024-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Sir', 'Sir'), ('Lady', 'Lady'), ('Miss', 'Miss'), ('Dame', 'Dame'), ('Lord', 'Lord'), ('Mr.', 'Mr.'), ('Mx', 'Mx'), ('Rev', 'Rev'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.')], max_length=5),
        ),
    ]
