# Generated by Django 5.1 on 2024-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Lord', 'Lord'), ('Miss', 'Miss'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx'), ('Rev', 'Rev'), ('Lady', 'Lady'), ('Ms.', 'Ms.'), ('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Sir', 'Sir')], max_length=5),
        ),
    ]
