# Generated by Django 5.1 on 2024-08-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0009_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mx', 'Mx'), ('Rev', 'Rev'), ('Sir', 'Sir'), ('Miss', 'Miss'), ('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Lady', 'Lady'), ('Lord', 'Lord'), ('Ms.', 'Ms.')], max_length=5),
        ),
    ]
