# Generated by Django 5.1 on 2024-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0011_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Rev', 'Rev'), ('Ms.', 'Ms.'), ('Lord', 'Lord'), ('Lady', 'Lady'), ('Miss', 'Miss'), ('Sir', 'Sir'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx'), ('Dame', 'Dame'), ('Dr.', 'Dr.')], max_length=5),
        ),
    ]
