# Generated by Django 5.1 on 2024-08-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx'), ('Lord', 'Lord'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Lady', 'Lady'), ('Sir', 'Sir'), ('Dame', 'Dame'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.')], max_length=5),
        ),
    ]
