# Generated by Django 5.1 on 2024-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0013_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Mrs.', 'Mrs.'), ('Sir', 'Sir'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Lady', 'Lady'), ('Mx', 'Mx'), ('Dame', 'Dame'), ('Ms.', 'Ms.'), ('Lord', 'Lord')], max_length=5),
        ),
    ]
