# Generated by Django 5.1 on 2024-08-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0018_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Lord', 'Lord'), ('Dr.', 'Dr.'), ('Rev', 'Rev'), ('Mx', 'Mx'), ('Dame', 'Dame'), ('Lady', 'Lady'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=5),
        ),
    ]
