# Generated by Django 5.1 on 2024-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0020_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Dame', 'Dame'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Miss', 'Miss'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Lord', 'Lord'), ('Rev', 'Rev'), ('Mx', 'Mx')], max_length=5),
        ),
    ]
