# Generated by Django 5.1 on 2024-08-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0025_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Ms.', 'Ms.'), ('Sir', 'Sir'), ('Dame', 'Dame'), ('Mx', 'Mx'), ('Miss', 'Miss'), ('Mr.', 'Mr.'), ('Lord', 'Lord'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Lady', 'Lady')], max_length=5),
        ),
    ]
