# Generated by Django 5.1 on 2024-08-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclass',
            options={'verbose_name_plural': 'University Classes'},
        ),
    ]
