# Generated by Django 5.1 on 2024-08-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=100)),
                ('Email', models.EmailField(blank=True, default='', max_length=300)),
                ('Username', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
