# Generated by Django 5.1 on 2024-08-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Sir', 'Sir'), ('Miss', 'Miss'), ('Rev', 'Rev'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Lady', 'Lady'), ('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Lord', 'Lord'), ('Mx', 'Mx')], max_length=5),
        ),
    ]
