# Generated by Django 5.1 on 2024-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0010_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss', 'Miss'), ('Dr.', 'Dr.'), ('Rev', 'Rev'), ('Dame', 'Dame'), ('Ms.', 'Ms.'), ('Mx', 'Mx'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Lord', 'Lord'), ('Mrs.', 'Mrs.')], max_length=5),
        ),
    ]
