# Generated by Django 5.1 on 2024-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0014_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Lord', 'Lord'), ('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Dame', 'Dame'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Rev', 'Rev'), ('Mx', 'Mx'), ('Sir', 'Sir'), ('Mrs.', 'Mrs.'), ('Lady', 'Lady')], max_length=5),
        ),
    ]
