# Generated by Django 5.1 on 2024-08-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0015_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Miss', 'Miss'), ('Lord', 'Lord'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Mx', 'Mx'), ('Ms.', 'Ms.'), ('Sir', 'Sir'), ('Lady', 'Lady'), ('Rev', 'Rev')], max_length=5),
        ),
    ]
