# Generated by Django 5.1 on 2024-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0016_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Lord', 'Lord'), ('Lady', 'Lady'), ('Mr.', 'Mr.'), ('Dame', 'Dame'), ('Miss', 'Miss'), ('Mx', 'Mx'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Sir', 'Sir'), ('Dr.', 'Dr.')], max_length=5),
        ),
    ]
