# Generated by Django 5.1 on 2024-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0017_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Rev', 'Rev'), ('Mx', 'Mx'), ('Lord', 'Lord'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Lady', 'Lady'), ('Miss', 'Miss')], max_length=5),
        ),
    ]
