# Generated by Django 5.1 on 2024-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0019_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Dame', 'Dame'), ('Sir', 'Sir'), ('Lord', 'Lord'), ('Miss', 'Miss'), ('Mr.', 'Mr.'), ('Lady', 'Lady'), ('Rev', 'Rev'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.')], max_length=5),
        ),
    ]
