# Generated by Django 5.1 on 2024-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0021_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Miss', 'Miss'), ('Mx', 'Mx'), ('Sir', 'Sir'), ('Mr.', 'Mr.'), ('Lady', 'Lady'), ('Lord', 'Lord'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Rev', 'Rev')], max_length=5),
        ),
    ]
