# Generated by Django 5.1 on 2024-08-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0022_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Lady', 'Lady'), ('Miss', 'Miss'), ('Mrs.', 'Mrs.'), ('Lord', 'Lord'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Mx', 'Mx'), ('Rev', 'Rev'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Dame', 'Dame')], max_length=5),
        ),
    ]
