# Generated by Django 5.1 on 2024-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0023_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Miss', 'Miss'), ('Rev', 'Rev'), ('Lord', 'Lord'), ('Ms.', 'Ms.'), ('Dame', 'Dame'), ('Lady', 'Lady'), ('Sir', 'Sir'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx')], max_length=5),
        ),
    ]
