# Generated by Django 5.1 on 2024-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0024_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Rev', 'Rev'), ('Lord', 'Lord'), ('Dame', 'Dame'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Mx', 'Mx'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Lady', 'Lady'), ('Sir', 'Sir')], max_length=5),
        ),
    ]
