# Generated by Django 5.1 on 2024-08-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0026_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Dame', 'Dame'), ('Rev', 'Rev'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mx', 'Mx'), ('Sir', 'Sir'), ('Lord', 'Lord'), ('Lady', 'Lady')], max_length=5),
        ),
    ]
